[build]
builder = "DOCKERFILE"
dockerfilePath = ".railway/Dockerfile"
buildCommand = "docker build -t misskey ."

[deploy]
startCommand = "pnpm run start"
healthcheckPath = "/api/ping"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1
